name: Generate Doxygen Docs

on:
  push:
    branches:
      - Stable  # Change if needed

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Generate Documentation
        run: doxygen docs/Doxyfile

      - name: move generated files
        run: mv docs/html/* ./docs
